# Generated by Django 3.0.2 on 2020-02-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0002_auto_20200202_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='owner',
            name='password',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
